### ISSUE TITLE
Allow communication between frontend and database

### ISSUE THREAD

**Issue by anthony-devarti** [anthony-devarti/sylvan-library#4]
this ticket spans across both repos and I can't figure it out to save my life.  Getting this to work is key, so we'll need some help.

This is done when ANY network call returns data from the backend.

**Comment by ast-epk** [comment]
I've picked this task up for my free cycles this week. I'm planning to try running on MySQL and then package a lightweight version that can use SQLite files.

**Comment by ast-epk** [comment]
MySQL connection test successful on commit 58ae840, detailed DB user and schema setup at the end of sylvan-library/README. Will write some simple DB connection calls at a later time.

**Comment by ast-epk** [comment]
## Database Initial Work

Node does not yet have sha2_password usage implemented, so we will need to set the password type to `mysql_native_password` for now.
This setup will allow sylvan to use node.js to connect to the underlying MySQL server. I am planning to determine a SQLite equivalent process once the SQL portion is setup (this will allow for a full-scale and lightweight version). In the meantime, I will add a Dockerfile which can build out the MySQL client and pass it the credentials and setup drafted below.

```
CREATE USER 'sylvan'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
CREATE DATABASE sylvandb;
GRANT ALL ON sylvandb.* TO sylvan;
FLUSH PRIVILEGES;
```

## Docker Container Work

Much of this may be somewhat outside the scope of the intention of this issue. I will probably split this off further to a separate "setup Docker environment for rollout anywhere" task. Notes for the past few commits below.

So far we have a Dockerfile that:
- Grabs the Debian:latest docker image
- Copies the sylvan-library codebase into the image
- Installs mysql, python3 and django
- Uses parts of the codebase to configure mysql
- Runs `npm install` within /var/www/sylvan-library

Right now, the docker container needs something to keep it alive when it is started from the image. Currently if we run the container without any stipulations it will immediately stop, because no processes are holding it in running status at the moment. The commands below are for testing the current build as we mess with it.

```
cd sylvan-library
docker build .
# Start the docker image as a container without auto-stopping (temporary)
docker run -dit (image-id)
# Access the container using the shell to peer into its guts
docker exec -it (image-id) /bin/bash
```

It is lacking an initializer script `CMD init` at the end, which will run the initial tasks for the container at startup. This will include a process that will keep it alive, most likely MySQL since we want that up as long as the container is in use.
In addition to starting the MySQL service, we should include a shell script at init to start the DB with a provided user/pass and any initial DB tables we may want to have for the app to access.

There is no web server setup to host the app in this Dockerfile, we could install something if that is needed, but for now this Dockerfile at least provides a rudimentary development/testing environment that can be run on anything with Docker installed.

**Comment by ast-epk** [comment]
One last note, before I hit the hay. I would like to take some time to try getting SQLite going as a buffer or cache for the app. It was initially going to be the backend for the app, and I think there are some places it can really provide a lot of utility. I imagine that the MySQL backend will allow us to expand, while the SQLite can handle in-between transactions and other things that MySQL may initially slow us down on.

To use SQLite with node we will need the sqlite3 package. I have written some Python and JS code somewhere that handles sqlite connection that I will try to find for reference.
